[project]
name = "domaintools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.9.3",
    "click>=8.0.0",
    "configparser>=5.0.0",
    "requests>=2.26.0",
    "rich>=10.0.0",
    "tinydb>=4.5.0",
]
